export const toyAT = {
  INIT_TOY_SAGA:'INIT_TOY_SAGA',
  INIT_TOY:'INIT_TOY',
  SEARCH_TOYS:'SEARCH_TOYS',
  FILTER_TYPE:'FILTER_TYPE',
  ADD_PURCHASE:'ADD_PURCHASE',
  SUBSTITUTE_PURCHASE:'SUBSTITUTE_PURCHASE',
  DELETE_PURCHASE:'DELETE_PURCHASE'
}

